# MySql Image
FROM mysql:latest

ENV MYSQL_DATABASE=accwe-hospital \
    MYSQL_USER=root \
    MYSQL_PASSWORD=root \
    MYSQL_ROOT_PASSWORD=root

# Inicialize db
COPY ./db-init.sql /docker-entrypoint-initdb.d/

# MySQL port
EXPOSE 3306
CMD ["mysqld"]
